spring.application.name=${APP_NAME}
spring.datasource.url=${DATASOURCE_URL}
spring.datasource.username=${DATASOURCE_USERNAME}
spring.datasource.password=${DATASOURCE_PASSWORD}
server.port=${PORT:8080}
spring.datasource.driver-class-name=${DATASOURCE_DRIVER_CLASS_NAME}

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=${JPA_HIBERNATE_DDL_AUTO}
spring.jpa.show-sql=${JPA_SHOW_SQL}
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}
frontend.url=${FRONTEND_URL}
